### ISSUE TITLE
Avoid handling a keyboard event if the defaultPrevented flag is true

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#163]
In the case if other listeners already handled an event then phosphor should not do anything, e.g. [here](https://github.com/phosphorjs/phosphor/blob/cb7a404ba6e40c49d379d97497c379ccebb52c79/src/ui/application.ts#L357) it should be: 
```ts
  protected evtKeydown(event: KeyboardEvent): void {
    if (!event.defaultPrevented) {
      super.evtKeydown(event);
    }
  }
```

**Comment by afshin** [comment]
As I understand it [`preventDefault()`](https://developer.mozilla.org/en/docs/Web/API/Event/preventDefault) is only intended to prevent the *browser's* default action. If a user wants to prevent further propagation of an event and to make sure it doesn't bubble up to the `application.ts` file, then they should be using *both* `preventDefault()` *and* [`stopPropagation()`](https://developer.mozilla.org/en/docs/Web/API/Event/stopPropagation):

```javascript
event.preventDefault();
event.stopPropagation();
```

**Comment by akosyakov** [comment]
@afshin you are right thne we will have it as a workaround in our code till monaco bug is closed: https://github.com/Microsoft/monaco-editor/issues/173

**Comment by sccolbert** [comment]
If another widget/component/whatever is handling keyboard events and *doesn't* want other things after it in the bubble path to handle those same events, then it should `stopPropagation()`. I'm not going to add this workaround to Phosphor because it would be incorrect behavior. 

You can workaround this Monaco problem in your own code by adding a `keydown` listener to your widget, and calling `stopPropagation()` on any event which has `defaultPrevented`.
