### ISSUE TITLE
VNode: custom attributes

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#175]
How to provide custom attributes?

**Comment by afshin** [comment]
The virtual DOM only supports standard attributes and `data-` attributes. If you want to create data attributes, you can use the `dataset` key in the node attributes at construction.

https://github.com/phosphorjs/phosphor/blob/84a0292/src/ui/vdom.ts#L1152-L1158

**Comment by akosyakov** [comment]
@afshin I need to set `incremental` attribute for an input element of `search` type. How can i do it?

**Comment by afshin** [comment]
Because the `incremental` attribute is non-standard and only works in Safari and Chrome, I suspect that @sccolbert would not want it in the virtual DOM code. My suggestion would be to set that attribute after your node has been rendered if you're willing to accept the limitation that it will not work as intended in Firefox and IE/Edge.

https://developer.mozilla.org/en/docs/Web/HTML/Element/input (search for `incremental` on this page to find it)

**Comment by akosyakov** [comment]
@afshin ok, thx

**Comment by sccolbert** [comment]
Yep. I'll add that attribute if it ever becomes widely adopted or standardized.
