### ISSUE TITLE
stretch default number default to 0 ? 

### ISSUE THREAD

**Issue by Carreau** [phosphorjs/phosphor#19]
So i'm playing with boxlayout, 

I figured the [addStretch](http://phosphorjs.github.io/docs/classes/phosphor.panels.boxpanel.html#addstretch) would add an elastic stretch. Though it seem to have a default value of 0, which make adding any other stretch with non default value completely collapse the default ones. It might be a design decision, in which case it's fine, and I can document it, or we might make the default 1 which make teh behavior a little less surprising.

**Comment by sccolbert** [comment]
It's set to the same default used for the optional `stretch` arg of `addWidget`. The effect is that, if you use the defaults for everything, it will work as expected. This is because the spacer item generated for `addStretch` has an expanding size policy which will take precedence over zero stretch items in the layout algorithm

This is the logic chain to follow:
https://github.com/phosphorjs/phosphor/blob/master/src/widgets/boxlayout.ts#L169
https://github.com/phosphorjs/phosphor/blob/master/src/widgets/spaceritem.ts#L67
https://github.com/phosphorjs/phosphor/blob/master/src/widgets/boxlayout.ts#L416
https://github.com/phosphorjs/phosphor/blob/master/src/widgets/layoutengine.ts#L118
https://github.com/phosphorjs/phosphor/blob/master/src/widgets/layoutengine.ts#L285

**Comment by sccolbert** [comment]
One could make the argument for `stretch` to not be optional. I would do that before changing the default to something other than zero.

**Comment by sccolbert** [comment]
Re-opened to collect more comments.
