### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by thiagodp** [phosphorjs/phosphor#205]
Please use [Semantic Versioning](http://semver.org/). Examples on the [PhosphorJS page](http://phosphorjs.github.io/) are not working with the last release.

BTW, what is the right release to use with the examples? Are you planning to update them?

**Comment by afshin** [comment]
PhosphorJS does use semantic versioning.

The examples page is currently out of date and the multiple phosphor repositories have been re-organized into a single repo with multiple packages under the `@phosphor` namespace. The examples *do* work with the last version of the individual packages (*i.e.*, `phosphor-tabs`, `phosphor-messaging`, *etc.*), so if you want to copy them verbatim, you can install those packages (*e.g.*, `npm install phosphor-tabs`).

Because the current development effort has been primarily focused on reaching the `1.0` release, the documentation and examples page has fallen a little bit behind, but it will be updated soon. So you may be better off waiting for the official `1.0` release.

**Comment by thiagodp** [comment]
Thanks for the clarification, @afshin.

However, it appears that some classes haved changed. For instance, `MenuItem` does not exist anymore (it is now `Menu.IItem`, right?). Some classes are in other files too.

I coud not run the [examples/menus](http://phosphorjs.github.io/examples/menus/), but I had only installed `phosphor` and tried to adapt the code. Is it necessary to install another package?

**Comment by afshin** [comment]
The current version of PhosphorJS is incompatible with the example code. The examples as they are currently written will only work with the older packages `phosphor-menus`, `phosphor-tabs`, *etc.*

So that code will need to be refactored a bit to work with the new version of PhosphorJS.

If you want an example that uses the newest version before waiting for the docs to be updated, you can check out the [example in the repo](https://github.com/phosphorjs/phosphor/blob/master/example/src/index.ts)

**Comment by thiagodp** [comment]
OK, thx.

**Comment by thiagodp** [comment]
Sorry, but I think this issue should not have being closed. [Semantic versioning](http://semver.org/) says:
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```
So if a incompatible API change made the examples stop working, the MAJOR version of PhosphorJS should have been increased, right? Otherwise, you are not using semantic versioning,

**Comment by sccolbert** [comment]
The examples do not use the `phosphor` package. So comparing versions between `phosphor` and `phosphor-widget` makes no sense. All of the various phosphor packages themselves (whether deprecated or not) follow semver.

**Comment by blink1073** [comment]
The key being that the packages *as installed on npm* are following semantic versioning.  We have been iterating on the best approach for a library of this size.

**Comment by thiagodp** [comment]
Understood. I had supposed that the examples were using `phosphor`.

**Comment by jjrv** [comment]
Also note that PhosphorJS currently advertises its version as 0.1.4 for the `widgets` package for example, and you link says:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

That's why 1.0.0 will be a big step, since afterwards they should commit to the API as published.
