### ISSUE TITLE
Widget.update - completion notification.

### ISSUE THREAD

**Issue by GordonSmith** [phosphorjs/phosphor#272]
The problem I am looking at is this:
* Resize widget
* call widget.update
* It ripples down to my web content via "onResize" which also performs an async re-render
* Question:  How to "cleanly" know when all the rendering has completed?

**Comment by sccolbert** [comment]
Why do you need to know when the rendering is complete?

**Comment by sccolbert** [comment]
Messages are intended to be fire-and-forget. In #271, I provide some code which you can use for custom messages which need to "return" a value to the sender. In general, caring about what a widget does during `update` is the wrong thing to do. There may be a better way to achieve your ultimate goal, if you're able to tell us what that is.

**Comment by GordonSmith** [comment]
Well its a little bit hypothetical (in my real work I would only be interested in knowing when the first render is complete):
* When rendering is complete I might want to "Save as PDF" if it was running in a headless browser (PhantomJS).
* I might have a "hotbar" which shows additional information based on what is below the mouse.

The initial render is of genuine interest though - and I suspect there is a better way for that?

**Comment by sccolbert** [comment]
In general, it's impossible to know when rendering is "done" in a "clean" way, because of all the various things which can be done to affect rendering such as CSS animations/transitions/progressive loading/font delays/etc. Attempting to address all of those edge cases would be an enormous task, and be a considerable slowdown to the stack, and may actually be impossible in some cases. What about just  using a sufficiently delayed timer after starting your app before snapping the PDF?

I'm not sure I understand the "hotbar" case. If you query the DOM on the mouse event, you get the most up-to-date information. If the widget updates between mouse events, the next mouse event will get the newest information.

**Comment by GordonSmith** [comment]
Yup been there - like I say not a show stopper by any means, I am just trying to fit together two frameworks which are similar(ish) and am very much feeling out phosphor...
