### ISSUE TITLE
grid scroll handle sometimes leaves horizontal lines when scrolling

### ISSUE THREAD

**Issue by jasongrout** [phosphorjs/phosphor#290]
In JLab 0.24.1 using the csv viewer, if I scroll up and down slowly while viewing a small file, sometimes the scroll handle will leave small horizontal lines in the scroll bar region (see screenshot)

<img width="32" alt="screen shot 2017-06-19 at 3 22 57 pm" src="https://user-images.githubusercontent.com/192614/27302020-4d825bac-5503-11e7-8298-2bba64c3f2c1.png">

These lines stay as long as the scroll handle doesn't go near them (though they might flicker). Clicking another tab and clicking back gets rid of them.

Small, I know, but I bet it will bug @sccolbert :).

I was running Chrome Version 58.0.3029.110 (64-bit) on OS X 10.11.6.

The file I was using was 

```
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
1,2,3
3,2,4
5,4,3
2,3,4
1,2,3
4,3,2
```

**Comment by jasongrout** [comment]
My browser just upgraded to Version 59.0.3071.104 (Official Build) (64-bit), and I can't reproduce this (and it was easy to reproduce it before).

So I'm okay closing this, and having it as a reference in case anyone else has this issue.

**Comment by sccolbert** [comment]
Yeah this is a rendering bug in chrome 58 that manifests when hardware
accelerated rendering is enabled. Unfortunately, there's nothing I can do
about it. Fortunately, it's fixed in canary :)

On Jun 19, 2017 2:31 PM, "Jason Grout" <notifications@github.com> wrote:

Closed #290 <https://github.com/phosphorjs/phosphor/issues/290>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/phosphorjs/phosphor/issues/290#event-1129747980>, or mute
the thread

**Comment by jasongrout** [comment]
Chrome 59 is stable now :).

**Comment by jpallas** [comment]
For what it's worth, I'm seeing a similar thing (with horizontal instead of vertical scrollbar) with Safari 11.1 on a Macbook Air.  Only shows up when the scrollbar is being moved to the left, not the right, and doesn't show up in Firefox.  (In [BeakerX](https://github.com/twosigma/beakerx))

![screen shot 2018-05-31 at 1 39 32 pm](https://user-images.githubusercontent.com/4623910/40807511-5951ef06-64d9-11e8-991d-056cfbdd2765.png)
