### ISSUE TITLE
Build failing: dragdrop package

### ISSUE THREAD

**Issue by maxgamurar** [phosphorjs/phosphor#312]
> @phosphor/dragdrop@1.3.0 build /home/max/Projects/Continuum/DOCs/OSS-Docs/phosphor/packages/dragdrop
> tsc

src/index.ts(226,7): error TS2322: Type 'Promise<string>' is not assignable to type 'Promise<DropAction>'.
  Type 'string' is not assignable to type 'DropAction'.

**Comment by blink1073** [comment]
Hi @maxgamurar, running the `tsc` command directly uses the global typescript compiler, while `npm run build` uses the version local to that [package](https://github.com/phosphorjs/phosphor/blob/23b9d075ebc5b73ab148b6ebfc20af97f85714c4/packages/dragdrop/package.json#L22).

**Comment by blink1073** [comment]
You can run `tsc --version` to check what your global version is, and run `npm install -g typescript@^2.3` to get it in sync with what phosphor is using.

**Comment by sccolbert** [comment]
Yeah. Typescript doesn't really follow semver, and this error is due to a backwards incompatible change made in Typescript 2.4. This is why we pin to a minor version (~2.3.0 currently) and use that over a globally installed `tsc` in our build scripts.

As for the direct issue, it will be fixed with the next release of Phosphor when we upgrade to Typescript 2.5
