### ISSUE TITLE
provide more "examples" of dockpanel

### ISSUE THREAD

**Issue by nimo23** [phosphorjs/phosphor#323]
I try to figure out the **differences** of http://phosphorjs.github.io/examples/dockpanel/ and http://golden-layout.com/. I want to choose the best in relation to performance and flexibility.

**So I have these questions:**
1. Does dockpanel support **dragging a tab from one panel to another?** (The example does not allow dragging tabs from one panel to another, only within a panel, tabs can be reordered).
2. Does dockpanel supports "maximizing a tab" to fullscreen within the window object? In http://phosphorjs.github.io/examples/dockpanel/, there is only a "close"-button. Would be nice to have these two buttons:
  - **"minimize":** minimzes tab and puts it to the bottom of the panel or window
  - **"maximize":** maximize tab to panel or window (and "restore"-button)
3. Can I add **more buttons within the tab-menu**? (For example, a color picker to colorize the tab contents background: http://golden-layout.com/examples/#e15391fb136593e265013408cf68e561)
4. Does dockpanel has **auto-layouts** build in (for example, **"golden grid"-layout** http://golden-layout.com/examples/#849a1cd2afcc95b474f621635ef5b590). Programmatic reorder: http://golden-layout.com/examples/#01249881a541bafcdf827c8b9020ad8a. Would be nice to provide layout-templates, so panels are rearranged based on golden grid or standard layouts (https://keen.github.io/dashboards/layouts/)
6. Does dockpanel supports **nested panels** (http://golden-layout.com/examples/#b40c19e79915493e9d3ae0220773358f)
7. Does dockpanel supports **native scroller** ? http://golden-layout.com/examples/#b8d8f23d4354d58f6a53f96a3e83753d
8. Can I use dockpanel in **typical react applications** ? As dockpanel wants to switch to virtual dom of react. I guess, dockpanel is fully compatible to react (render(), lifecycle,..). Right?
9. Does **"dockpanel" supports "touch"** (for example, when using "dockpanel" within a tablet)
10. Does dockpanel uses simple "js-object (json)" for all configurations states/props (window/panel/tab-position,size, ...). For example, "goldenGrid" uses simple config-object to (re)store its window-layout and its iternal state of each tab:

```
// adapted from http://golden-layout.com/examples/#XdabGJ
var config = {
    content: [{
        type: 'row',
        content: [{
      title: 'Users',
            type:'react-component',
            component: 'user-list'
        },{
      title: 'User Detail',
            type:'react-component',
            component: 'user-detail'
        }]
    }]
};

var myLayout = new GoldenLayout( config );
```

10. Maybe the author could also **highlight the other main differences** between http://golden-layout.com/ and http://phosphorjs.github.io/examples/dockpanel/.

**11. And if some of the above points are actually not supported by "dockpanel", are the points in the roadmap?**

Thanks in advance.

**Comment by kayvanbree** [comment]
Currently I'm trying to get DockPanels to work within Angular. I have seen comments of people who did this, but with way older versions of both Angular and PhosphorJS. A tutorial about how this could be done would also be nice.

**Comment by stoplion** [comment]
Provide more "examples" of everything?

**Comment by stoplion** [comment]
There is an example with React here. http://phosphorjs.github.io/examples/todomvc/#/ I have no idea if it is up to date. Also I don't think you can use JSX with it..

**Comment by sccolbert** [comment]
> I want to choose the best in relation to performance and flexibility.

Phosphor's dock panel is substantially faster and less buggy than golden layout.

> Does dockpanel support dragging a tab from one panel to another? (The example does not allow dragging tabs from one panel to another, only within a panel, tabs can be reordered).

Yes. Drag a tab to the *center* of the panel you want to add it to. See the gif below:

![tabify](https://user-images.githubusercontent.com/137289/34836350-4a36607c-f6bd-11e7-8896-0b239cee3e26.gif)

In fact Phosphor supports *four additional* docking positions which golden layout does not have. These are on the *perimeter* of the dock panel. The reason the "tab" zone is in the center of a panel, is because it would otherwise conflict with the top perimeter zone. See the gif below:

![perimeter](https://user-images.githubusercontent.com/137289/34837700-4121f664-f6c1-11e7-9492-d4cbb5a6f07b.gif)


> Does dockpanel supports "maximizing a tab" to fullscreen within the window object? In http://phosphorjs.github.io/examples/dockpanel/, there is only a "close"-button. Would be nice to have these two buttons:

It supports what we call "single document mode", which is something you can activate programmatically: 
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L161

In JupyterLab, we've setup a `Cmd-Shift-Enter` shortcut to toggle this mode. See the gif below:

![maximize](https://user-images.githubusercontent.com/137289/34837786-81fd90c6-f6c1-11e7-93d6-2d82f40a8ca5.gif)

> Can I add more buttons within the tab-menu

The dock panel supports a custom renderer option, which can be used to supply custom tab bar widgets. You can add extra DOM nodes to a tab bar widget's `.node`, provided you do not modify the contents of it's `.contentNode`. You can *also* supply a custom renderer to a tab bar, which controls how the tabs themselves are rendered:

DockPanel Options:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L966-L971
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L1179-L1211

TabBar Options:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/tabbar.ts#L1134-L1139
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/tabbar.ts#L1273-L1446
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/tabbar.ts#L286-L296

> Does dockpanel has auto-layouts build in

No, but you can use the `restoreLayout()` method to change the layout in-bulk. This is how "single document mode" is implemented under the covers, and it's also how we save/restore the layout in JupyterLab. You could simply write a few functions yourself which generate the layout tree for your "predefined layouts", then call `restoreLayout()` with that tree.

https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L294-L306

> Does dockpanel supports nested panels

No, but the example you linked seems to be buggy (I can get stacks and panels to disappear, etc.), so I'm not sure exactly what functionality you want here. You *can* put a dock panel inside a separet `TabPanel` if you wanted to. But my thoughts on this is that the best UX is to only have one `DockPanel` in an app.

> Does dockpanel supports native scroller

Of course. The dock panel doesn't care what child widgets you put inside of it. Those child widgets handle their own scrolling. See the gif below:

![scrolling](https://user-images.githubusercontent.com/137289/34837109-6e4c39bc-f6bf-11e7-9748-ed7c317df26f.gif)

> Can I use dockpanel in typical react applications

You can use *any* phosphor widget in *any* framework which supports embedding of arbitrary foreign content. You simply call `Widget.attach(myPhosphorWidget, otherFrameworkDomNode)` at the appropriate time for your framework. Depending on the widget, you *may* need to inform the widget when *it is likely to have been resized*, so that it can lay out its children appropriately. For the `DockPanel` the simplest thing to do is call `myDockPanel.update()` from a window `resize` event listener.

https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/widget.ts#L978-L996

> Does "dockpanel" supports "touch"

"yes" insofar as your mobile browser maps touch events to mouse events. The DockPanel was designed with the desktop in mind and uses mouse events internally. It was built before the pointer events spec was finalized. Once pointer events are well supported by all major browsers, I plan to transition to pointer events internally, which will increase support for mobile browsers.

> Does dockpanel uses simple "js-object (json)" for all configurations states/props (window/panel/tab-position,size, ...).

See the above comment about `restoreLayout()`. The config object there is *mostly* JSON, with the exception of the widget's themselves. Phosphor doesn't make decisions for you about how to serialize your widgets. If you need full JSON serialization, you need to write your own function which takes a layout config, and returns a new structure with your serialized widgets. We do this in JupyterLab in order to store the user config in a database.

> Maybe the author could also highlight the other main differences

Faster, less buggy, more docking positions, integrates better with the rest of phosphor.

**Comment by sccolbert** [comment]
> Currently I'm trying to get DockPanels to work within Angular. I have seen comments of people who did this, but with way older versions of both Angular and PhosphorJS. A tutorial about how this could be done would also be nice.

I'm not familiar with the details of Angular, but like my previous post mentioned, it boils down to:
  1. Calling `Widget.attach(myWidget, myHostNode)` at the right time for your framework.
  2. If `myWidget` is a panel, calling `myWidget.update()` when the widget is *likely to have been resized* (typically from a window `resize` listener).

**Comment by nimo23** [comment]
Thanks, I will use this against the other. It s awesome!

**Comment by sccolbert** [comment]
Awesome. Thanks!

**Comment by torbgy** [comment]
hey! I've been reading through the issues trying to figure out how to make the sidebar panel, which @sccolbert has in this figures, how can one include this? and is this sidebar panel expandable (hide/show)?

if it's unclear, I'm thinking of the vertical sidebar :)
