### ISSUE TITLE
Async command `isEnabled`

### ISSUE THREAD

**Issue by amiramw** [phosphorjs/phosphor#369]
It could be usefull if the `isEnabled` logic of a command could be asynchronous.
Of course it means that many flows would have to change to work with async functions.

**Comment by jasongrout** [comment]
> It could be usefull if the `isEnabled` logic of a command could be asynchronous.

Can you give some concrete examples of situations where it would be really useful?

**Comment by sccolbert** [comment]
At this point, it's not going to happen due to the breakage it would cause.
I did think about think about making commands async in the beginning, but
decided against it for a variety of reasons; the big one being that it
makes life much harder when writing widgets which consume commands. They
need to update their UI "now" with that info, not later. For the rare case
where a command has async behavior, it can be handled internally by the
command author via `notifyCommandChanged`.

**Comment by amiramw** [comment]
Thanks for the info.
