### ISSUE TITLE
bogus keyboard focussing in splitpanel after move

### ISSUE THREAD

**Issue by akosyakov** [phosphorjs/phosphor#398]
I use `tabIndex` to make some element focusable with a keyboard according to order in HTML element flow. Unfortunately it does not work if a widget is moved in the split panel. Move introduces a mismatch between order of elements in the HTML and in the layout.

**Comment by akosyakov** [comment]
work it around by implementing custom `moveWidget` which aligns HTML with the layout model

**Comment by sccolbert** [comment]
You should change your `tabIndex` values rather than rearranging the HTML. Phosphor layouts which use `absolute` positioning make many optimizations to avoid causing DOM reflows. The issue you are seeing is one of those optimizations. There is no need for DOM order to match position order, so moving a panel position does not require changing the actual DOM structure.

**Comment by akosyakov** [comment]
> You should change your tabIndex values rather than rearranging the HTML. 

Do you mean to assign `tabIndex` greater than 0? It seems to be a common anti-pattern: https://web.dev/control-focus-with-tabindex#avoid-tabindex-greater-0

**Comment by akosyakov** [comment]
We've tried `tabIndex`. It breaks accessibility. `tabIndex` is a global, so order is completely messed up, especially if added widgets also define own `tabIndex` greater 0. Please consider to reopen.
