### ISSUE TITLE
Allow a drop target to scroll within a parent node

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor#88]
For example, dragging a cell into a notebook should allow the notebook content to scroll.

cf https://github.com/jupyter-incubator/dashboards/pull/204/files

migrated from https://github.com/phosphorjs/phosphor-dragdrop/pull/5

**Comment by sccolbert** [comment]
The drag image location is now correct in the presence of scrolled body content. Since mousewheel events are not blocked during drag, you can still scroll while dragging. Auto-scroll while dragging is fraught with problems because multiple widgets can have scrollbars and content which *shouldn't* be scrolled.

Should we keep this open? Is there strong demand for this?

**Comment by blink1073** [comment]
We have our own utility [class](https://github.com/jupyterlab/jupyterlab/blob/07ec775b042386593e40347558ef170dab8e58e1/src/common/dragscroll.ts) in JupyterLab for this, which is what allows us to find the proper spot to drop a cell in a scrolling notebook.

**Comment by blink1073** [comment]
Happy to keep it there if you like.

**Comment by sccolbert** [comment]
that may be a good utility class to add to the dragdrop package.
